// A Dagger reference module demonstrating basic module concepts and return types.
//
// This module serves as a learning template showing how to return strings,
// chain containers, generate files, and use default or optional arguments.
package main

import (
	"context"
	"dagger/hello/internal/dagger"
	"fmt"
)

const (
	defaultImageRepository = "cgr.dev/chainguard/wolfi-base:latest"
)

// Hello provides greeting and demonstration functions.
type Hello struct {
	// +private
	Image string
	// +private
	Greeting string
	// +private
	Ctr *dagger.Container
}

// New creates a new instance of the Hello module.
func New(
	// Custom image reference in "repository:tag" format.
	// +optional
	image string,
	// Default greeting word to use (e.g. "Hello", "Hola", "Szia").
	// +default="Hello"
	// +optional
	greeting string,
) *Hello {
	return &Hello{
		Image:    image,
		Greeting: greeting,
	}
}

// container returns the underlying Dagger container, lazily initialized.
func (m *Hello) container() *dagger.Container {
	if m.Ctr != nil {
		return m.Ctr
	}

	image := m.Image
	if image == "" {
		image = defaultImageRepository
	}

	m.Ctr = dag.Container().From(image)
	return m.Ctr
}

// Message returns a greeting string using pure Go (runs instantly without containers).
func (m *Hello) Message(
	// Name of the person or entity to greet.
	// +default="Daggerverse"
	// +optional
	name string,
) string {
	return fmt.Sprintf("%s, %s!", m.Greeting, name)
}

// Say executes an echo command inside the container and returns stdout.
func (m *Hello) Say(
	ctx context.Context,
	// Name to greet inside the container.
	// +default="Daggerverse"
	// +optional
	name string,
) (string, error) {
	msg := fmt.Sprintf("%s, %s!", m.Greeting, name)
	return m.container().
		WithExec([]string{"echo", msg}).
		Stdout(ctx)
}

// Terminal returns the container prepared with the message, ready for chaining or interactive shell.
func (m *Hello) Terminal(
	// Message to echo when container starts.
	// +default="Welcome to Dagger!"
	// +optional
	message string,
) *dagger.Container {
	return m.container().
		WithExec([]string{"echo", message})
}

// Write generates a greeting text file inside Dagger and returns it as an artifact.
func (m *Hello) Write(
	// Name to greet in the generated file.
	// +default="Daggerverse"
	// +optional
	name string,
) *dagger.File {
	content := fmt.Sprintf("%s, %s!\nGenerated by Dagger.\n", m.Greeting, name)

	return dag.Directory().
		WithNewFile("greeting.txt", content).
		File("greeting.txt")
}
