// Package main provides tests for the Hello reference module.
package main

import (
	"context"
	"dagger/hello/test/internal/dagger"
	"errors"
	"strings"

	"github.com/sourcegraph/conc/pool"
)

// Test provides tests for the Hello module.
type Test struct{}

// All runs all tests concurrently.
func (m *Test) All(ctx context.Context) error {
	p := pool.New().WithErrors().WithContext(ctx)

	p.Go(m.TestMessage)
	p.Go(m.TestSay)
	p.Go(m.TestTerminal)
	p.Go(m.TestWrite)
	p.Go(m.TestCustomGreeting)

	return p.Wait()
}

// TestMessage asserts that the pure Go Message function returns the expected string.
func (m *Test) TestMessage(ctx context.Context) error {
	msg, err := dag.Hello().Message(ctx)
	if err != nil {
		return err
	}

	if msg != "Hello, Daggerverse!" {
		return errors.New("unexpected message output: " + msg)
	}
	return nil
}

// TestSay asserts that the container execution produces the correct stdout.
func (m *Test) TestSay(ctx context.Context) error {
	stdout, err := dag.Hello().Say(ctx, dagger.HelloSayOpts{
		Name: "Gopher",
	})
	if err != nil {
		return err
	}

	if !strings.Contains(stdout, "Hello, Gopher!") {
		return errors.New("expected stdout to contain 'Hello, Gopher!', got: " + stdout)
	}
	return nil
}

// TestTerminal asserts that the returned container executes successfully.
func (m *Test) TestTerminal(ctx context.Context) error {
	_, err := dag.Hello().Terminal().Sync(ctx)
	return err
}

// TestWrite asserts that a valid file artifact is generated with expected contents.
func (m *Test) TestWrite(ctx context.Context) error {
	file := dag.Hello().Write()
	content, err := file.Contents(ctx)
	if err != nil {
		return err
	}

	if !strings.Contains(content, "Generated by Dagger.") {
		return errors.New("file content does not match expected output")
	}
	return nil
}

// TestCustomGreeting tests the constructor options.
func (m *Test) TestCustomGreeting(ctx context.Context) error {
	msg, err := dag.Hello(dagger.HelloOpts{
		Greeting: "Hello",
	}).Message(ctx, dagger.HelloMessageOpts{
		Name: "World",
	})
	if err != nil {
		return err
	}

	if msg != "Hello, World!" {
		return errors.New("expected 'Hello, World!', got: " + msg)
	}
	return nil
}
