---
name: dagger-test

run-name: Dagger-Test

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  skip_duplicate_actions:
    name: Skip Duplicate Actions
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cancel_others: true
          concurrent_skipping: never

  dagger_test:
    name: Dagger Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - actionlint
          - editorconfig
          - hadolint
          - hello
          - quarto
          - revive
          - ruff
          - shellcheck
          - yamllint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get constructor args
        uses: dkershner6/switch-case-action@v1
        id: constructor-args
        with:
          default: ""
          conditionals-with-values: |
            ${{ matrix.module == 'gh' }} => --github-token env:GITHUB_TOKEN

      - name: Test Dagger module
        uses: dagger/dagger-for-github@v7
        with:
          verb: call
          module: github.com/${{ github.repository }}/${{ matrix.module }}/test@${{ github.ref }}
          args: ${{ steps.constructor-args.outputs.value }} all
          version: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
